name:                fltkhs-themes
version:             0.2.0.3
github:              "deech/fltkhs-themes"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"
build-type:          Custom
category:            UI,Graphics,GUI,User Interfaces
synopsis:            A set of themed widgets that provides drop in replacements to the ones in FLTKHS.
extra-source-files:
- README.org
data-files:
- fonts/*.ttf
- images/*.png
extra-doc-files:
- doc/images/*.png
description:         Please see the README on Github at <https://github.com/deech/fltkhs-themes#readme>

custom-setup:
  dependencies:
  - base >= 4.4
  - Cabal >= 2.4.0.0 && < 4

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - load-font >= 0.1.0.3
    - fltkhs >= 0.8.0.3
    - text >= 1.2.2.0
    - vector >= 0.12.0.1
    - bytestring
  ghc-options: -Wall -fno-warn-name-shadowing
  when:
    - condition: os(linux)
      extra-libraries: fontconfig
