#include <stdio.h>
#include <Fl_C.h>
#include <Fl_Types.h>
#include <Fl_EnumerationsC.h>
#include <Fl_AskC.h>
#include <Fl_BitmapC.h>
#include <Fl_BoxC.h>
#include <Fl_BrowserC.h>
#include <Fl_ButtonC.h>
#include <Fl_Check_ButtonC.h>
#include <Fl_ChoiceC.h>
#include <Fl_ClockC.h>
#include <Fl_Color_ChooserC.h>
#include <Fl_DeviceC.h>
#include <Fl_Double_WindowC.h>
#include <Fl_DrawC.h>
#include <Fl_ExportMacros.h>
#include <Fl_File_BrowserC.h>
#include <Fl_File_ChooserC.h>
#include <Fl_File_IconC.h>
#include <Fl_File_InputC.h>
#include <Fl_Float_InputC.h>
#include <Fl_Gl_WindowC.h>
#include <Fl_GroupC.h>
#include <Fl_Hold_BrowserC.h>
#include <Fl_Hor_SliderC.h>
#include <Fl_Hor_Value_SliderC.h>
#include <Fl_ImageC.h>
#include <Fl_InputC.h>
#include <Fl_Input_C.h>
#include <Fl_Int_InputC.h>
#include <Fl_Light_ButtonC.h>
#include <Fl_Menu_BarC.h>
#include <Fl_Menu_C.h>
#include <Fl_Menu_ItemC.h>
#include <Fl_Multi_BrowserC.h>
#include <Fl_Multiline_InputC.h>
#include <Fl_Multiline_OutputC.h>
#include <Fl_Native_File_ChooserC.h>
#include <Fl_OutputC.h>
#include <Fl_Overlay_WindowC.h>
#include <Fl_PNM_ImageC.h>
#include <Fl_Paged_DeviceC.h>
#include <Fl_PixmapC.h>
#include <Fl_PreferencesC.h>
#include <Fl_PrinterC.h>
#include <Fl_ProgressC.h>
#include <Fl_RGB_ImageC.h>
#include <Fl_Radio_ButtonC.h>
#include <Fl_Radio_Light_ButtonC.h>
#include <Fl_Repeat_ButtonC.h>
#include <Fl_Return_ButtonC.h>
#include <Fl_Round_ButtonC.h>
#include <Fl_Round_ClockC.h>
#include <Fl_Secret_InputC.h>
#include <Fl_Select_BrowserC.h>
#include <Fl_Shared_ImageC.h>
#include <Fl_Single_WindowC.h>
#include <Fl_SliderC.h>
#include <Fl_Sys_Menu_BarC.h>
#include <Fl_TableC.h>
#include <Fl_Table_RowC.h>
#include <Fl_TabsC.h>
#include <Fl_Text_BufferC.h>
#include <Fl_Text_DisplayC.h>
#include <Fl_Text_EditorC.h>
#include <Fl_Text_SelectionC.h>
#include <Fl_TileC.h>
#include <Fl_Toggle_ButtonC.h>
#include <Fl_TooltipC.h>
#include <Fl_TreeC.h>
#include <Fl_Tree_ItemC.h>
#include <Fl_Tree_PrefsC.h>
#include <Fl_ValuatorC.h>
#include <Fl_Value_InputC.h>
#include <Fl_Value_SliderC.h>
#include <Fl_WidgetC.h>
#include <Fl_WindowC.h>
#include <Fl_WizardC.h>
#include <filenameC.h>
#include <fl_show_colormapC.h>
#include <glC.h>
#include <glutC.h>
#include <xC.h>

int main(int argc, char** argv) {
  return 0;
}
